version: '3'
services:
  pgadmin_server:
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "geodocs@coppevale.com.br"
      PGADMIN_DEFAULT_PASSWORD: "geodocs"
    ports:
      - "5050:80"
    volumes:
      - ~/data/pgadmin4:/var/lib/pgadmin/storage/

  db_bananas:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=banana
      - POSTGRES_PASSWORD=bananadepijama
      - POSTGRES_DB=bananal
    ports:
      - "2384:5432"
    networks:
      tnet:
        aliases:
          - bananas_db
    volumes:
      - ~/data/bananas/db:/var/lib/postgresql/data

networks:
  tnet:
    external: true

