version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - "9091:80"
    networks:
      tnet:
        aliases:
          - bananas_api
    volumes:
      - .:/app
    depends_on:
      - db_bananas

  db_bananas:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=banana
      - POSTGRES_PASSWORD=bananadepijama
      - POSTGRES_DB=bananal
    ports:
      - "2384:5432"
    networks:
      tnet:
        aliases:
          - bananas_db
    volumes:
      - ~/data/bananas/db:/var/lib/postgresql/data
      # - pgdata:/var/lib/postgresql/data

networks:
  tnet:
    external: true

