version: '3'
services:
  pgadmin_server:
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "geodocs@coppevale.com.br"
      PGADMIN_DEFAULT_PASSWORD: "geodocs"
    ports:
      - "5050:80"
    volumes:
      - ~/data/pgadmin4:/var/lib/pgadmin/storage/
    networks:
      tnet:
        aliases:
          - pgadmin

networks:
  tnet:
    external: true
